# Generated by Django 5.1.5 on 2025-02-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_email',
            new_name='org_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='org_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='org_name',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
