# Generated by Django 5.1.5 on 2025-02-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_profile_email_profile_org_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_phone',
            field=models.IntegerField(null=True),
        ),
    ]
