# Generated by Django 5.1.5 on 2025-02-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='full_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='contact_info',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='financing_type',
            field=models.CharField(choices=[('local', 'Lokalne działania'), ('local_initiative', 'Inicjatywa lokalna'), ('own_resources', 'Z własnych środków'), ('other', 'Inne')], default='other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='financing_type_other',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('bobrek', 'Bobrek'), ('gorecko', 'Górecko'), ('gorniki', 'Górniki'), ('karb', 'Karb'), ('lagiewniki', 'Łagiewniki'), ('miechowice', 'Miechowice'), ('osiedle_zietka', 'Osiedle gen. Jerzego Ziętka'), ('rozbark', 'Rozbark'), ('srodmiescie', 'Śródmieście'), ('stolarzowice', 'Stolarzowice'), ('stroszek_dabrowa', 'Stroszek-Dąbrowa Miejska'), ('sucha_gora', 'Sucha Góra'), ('szombierki', 'Szombierki')], default='bobrek', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='people_involved_nb',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='proj_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='defult', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='year_of_completion',
            field=models.PositiveSmallIntegerField(default=1234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='bbi_app.tag'),
        ),
    ]
