# Generated by Django 5.1.5 on 2025-09-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_app', '0003_project_image1_project_image2_project_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='people_involved_nb',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
    ]
