# Generated by Django 5.1.5 on 2025-10-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_app', '0005_remove_project_proj_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='project',
            name='financing_type',
            field=models.CharField(choices=[('local', 'Lokalne działania'), ('local_initiative', 'Inicjatywa lokalna'), ('own_resources', 'Z własnych środków'), ('no_financing', 'Realizacja bez finansowania'), ('other', 'Inne')], max_length=20),
        ),
    ]
