# Generated by Django 5.1.5 on 2025-10-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_app', '0008_alter_project_image1_alter_project_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Zatwierdzony'),
        ),
    ]
