# Generated by Django 5.1.5 on 2025-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_app', '0009_project_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
