# Generated by Django 5.1.5 on 2025-11-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_app', '0010_project_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization_name',
            field=models.CharField(default=(1, 'brak'), max_length=250),
            preserve_default=False,
        ),
    ]
