# Generated by Django 5.1.5 on 2025-12-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbi_app', '0011_alter_project_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do powiadomień'),
        ),
    ]
